#!/bin/bash

function check_grids {
	local link

	for link in $(ag --only-matching "\:link\:.*\.md" ${_MARKDOWN_FILE_NAME})
	do
		_LINK_FILE_NAME=$(echo ${link} | cut -d':' -f3 | sed 's/\ //g')

		if ! ls "${_LINK_FILE_NAME}"
		then
			echo_broken_link "Grid link"
		fi
	done
}

function check_images {
	local link

	for link in $(ag --only-matching "\[.+?\]\(.*?\.(gif|jpg|png)\)" ${_MARKDOWN_FILE_NAME})
	do
		_LINK_FILE_NAME=$(echo ${link} | sed 's/\[.*\](\(.*\.\(gif\|jpg\|png\)\).*)/\1/g')

		use_english_resource

		if ! ls "${_LINK_FILE_NAME}" || [[ ${_LINK_FILE_NAME} != *"/images/"* ]]
		then
			echo_broken_link "Image link"
		fi
	done
}

function check_includes {
	local link

	for link in $(ag --only-matching ".*include\}.*" ${_MARKDOWN_FILE_NAME})
	do
		_LINK_FILE_NAME=$(echo ${link} | sed 's/.*include\}\(.*\)/\1/g' | sed 's/ //g')

		local generated_code_warning
		local link_type

		if [[ $(echo ${link} | sed 's/.*{\(.*\)}.*/\1/g') == "literalinclude" ]]
		then
			link_type="Literal include"

			use_english_resource

			local resources_dir_name=$(echo ${_LINK_FILE_NAME} | sed 's/\(.*\/resources\/\).*/\1/g')

			if [[ $(ag -g .*service\.xml ${resources_dir_name} 2>/dev/null) ]]
			then
				generated_code_warning="Warning: this may reference code generated by service builder"
			fi

			if [[ $(ag --file-search-regex "update_example\.sh" "generate_custom_element" ${resources_dir_name} 2>/dev/null) && ! $(ag --files-with-matches liferay-.*-overlay 2>/dev/null) ]]
			then
				generated_code_warning="Warning: this may reference code generated by generate_custom_element"
			fi
		else
			link_type="Include"

			_LINK_FILE_NAME=$(echo $(git rev-parse --show-toplevel)/docs/${1}${_LINK_FILE_NAME} | sed 's,//,/,g')
		fi

		if ! ls "${_LINK_FILE_NAME}"
		then
			echo_broken_link ${link_type} ${generated_code_warning}
		fi
	done
}

function check_landing_pages {
	local landing_page_reference

	for landing_page_reference in $(ag --no-filename --no-numbers "\:file\:.*landing\.html" ${_MARKDOWN_FILE_NAME})
	do
		local landing_page_link_file_name=$(echo ${landing_page_reference} | sed 's/\:file\://g' | sed 's/\ //g')

		local link

		for link in $(ag --no-filename "url\:" ${landing_page_link_file_name})
		do
			if [[ ${link} != *"https://"* ]]
			then
				local link_file_name=$(echo ${link} \
					| sed "s/.*\('\|\"\)\(.*\)\('\|\"\|\#\).*/\2/g" \
					| sed 's/\(.*\)#.*/\1/g' | sed 's/\.html/\.md/g' \
				)

				if ! ls "${link_file_name}"
				then
					echo "Landing page link:"
					echo "    Landing page reference: ${landing_page_link_file_name}"
					echo "    Link: ${link_file_name/.md/.html}"
					echo
				fi
			fi
		done
	done
}

function check_markdown {
	local links

	for links in $(ag --only-matching '\[.*\]\((?!http).*\.md.*\).*' ${_MARKDOWN_FILE_NAME})
	do
		for _LINK_FILE_NAME in $(echo ${links} | sed -e 's/\.md)/\.md)\n/g' | sed 's/.*\](\(.*\.md\).*).*/\1/g')
		do
			if [[ ${_LINK_FILE_NAME} == *".md" ]]
			then
				if ! ls "${_LINK_FILE_NAME}"
				then
					echo_broken_link "Markdown link"
				fi
			fi
		done
	done
}

function check_tocs {
	local link

	for link in $(ag --only-matching "(?s)toc\:.*^---$" ${_MARKDOWN_FILE_NAME} | ag --nomultiline --nonumbers ".*\.md$")
	do
		_LINK_FILE_NAME=$(echo "${link}" | rev | cut -d' ' -f1 | rev)

		if ! ls "${_LINK_FILE_NAME}"
		then
			echo_broken_link "TOC link"
		fi
	done
}

function echo_broken_link {
	if [[ -z ${_CURRENT_MARKDOWN_FILE_NAME} || ${_CURRENT_MARKDOWN_FILE_NAME} != ${_MARKDOWN_FILE_NAME} ]]
	then
		_CURRENT_MARKDOWN_FILE_NAME=${_MARKDOWN_FILE_NAME}

		echo $(git rev-parse --show-prefix | cut -d'/' -f2-)${_MARKDOWN_FILE_NAME}
		echo
	fi

	_LINK_FILE_NAME=$(echo ${_LINK_FILE_NAME} | sed 's/.*liferay-learn\/docs\///g' | sed 's/\/\.\//\//g')

	if ! [ -z ${2} ]
	then
		echo "    ${2}"
	fi
	echo "    ${1}: ${_LINK_FILE_NAME}"
	echo
}

function ls {
	command ls "$@" > /dev/null 2>&1
}

function main {
	IFS=$'\n'

	if [ -z ${1} ]
	then
		echo "Usage: ./check_links.sh dxp/latest/en"

		exit 0
	fi

	local markdown_dir_name

	for markdown_dir_name in $(find ${1} -name '*.md' -printf '%h\n' | sort -u)
	do
		pushd ${markdown_dir_name} > /dev/null

		for _MARKDOWN_FILE_NAME in $(find . -maxdepth 1 -name "*.md" -printf '%f\n')
		do
			check_grids
			check_images ${1}
			check_includes ${1}
			check_landing_pages
			check_markdown
			check_tocs
		done

		popd > /dev/null
	done

	unset IFS
}

function use_english_resource {
	local language_code=$(pwd ${_MARKDOWN_FILE_NAME} | sed 's,.*/\(en\|ja\|ko\)/.*,\1,g')

	if [[ ${language_code} != "en" ]]
	then
		_LINK_FILE_NAME=$(pwd ${_LINK_FILE_NAME})/${_LINK_FILE_NAME}

		_LINK_FILE_NAME=$(echo ${_LINK_FILE_NAME} | sed "s,/${language_code}/,/en/,g")
	fi
}

main "${@}"